service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:
  jaeger_query:
    storage:
      traces: some_storage
    base_path: /
    ui:
      config_file: /jaeger/ui-config.json
      log_access: true
    http:
      endpoint: 0.0.0.0:16686
  jaeger_storage:
    backends:
      some_storage:
        memory:
          max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  tail_sampling:
    decision_wait: 5s
    policies:
      [
        {
          name: filter-by-attribute,
          type: string_attribute,
          string_attribute: { key: service.name, values: [telli-dialog, telli-admin] },
        },
        {
          name: drop-next-static,
          type: drop,
          drop:
            {
              drop_sub_policy:
                [
                  {
                    name: drop-next-static-sub-1,
                    type: string_attribute,
                    string_attribute:
                      { key: http.target, values: [\/_next\/static], enabled_regex_matching: true },
                  },
                ],
            },
        },
      ]

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
