CREATE INDEX "conversation_message_file_mapping_conversationMessageId_index" ON "conversation_message_file_mapping" USING btree ("conversationMessageId");--> statement-breakpoint
CREATE INDEX "text_chunk_file_id_index" ON "text_chunk" USING btree ("file_id");--> statement-breakpoint
CREATE INDEX "voucher_federal_state_id_index" ON "voucher" USING btree ("federal_state_id");--> statement-breakpoint
CREATE INDEX "voucher_redeemed_by_index" ON "voucher" USING btree ("redeemed_by");--> statement-breakpoint
CREATE INDEX "character_user_id_index" ON "character" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "character_school_id_index" ON "character" USING btree ("school_id");--> statement-breakpoint
CREATE INDEX "character_template_mappings_character_id_index" ON "character_template_mappings" USING btree ("character_id");--> statement-breakpoint
CREATE INDEX "character_template_mappings_federal_state_id_index" ON "character_template_mappings" USING btree ("federal_state_id");--> statement-breakpoint
CREATE INDEX "conversation_message_conversation_id_index" ON "conversation_message" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "conversation_message_user_id_index" ON "conversation_message" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "conversation_user_id_index" ON "conversation" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "conversation_character_id_index" ON "conversation" USING btree ("character_id");--> statement-breakpoint
CREATE INDEX "conversation_custom_gpt_id_index" ON "conversation" USING btree ("custom_gpt_id");--> statement-breakpoint
CREATE INDEX "conversation_usage_tracking_conversation_id_index" ON "conversation_usage_tracking" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "conversation_usage_tracking_user_id_index" ON "conversation_usage_tracking" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "conversation_usage_tracking_created_at_index" ON "conversation_usage_tracking" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "custom_gpt_user_id_index" ON "custom_gpt" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "custom_gpt_school_id_index" ON "custom_gpt" USING btree ("school_id");--> statement-breakpoint
CREATE INDEX "custom_gpt_template_mappings_custom_gpt_id_index" ON "custom_gpt_template_mappings" USING btree ("custom_gpt_id");--> statement-breakpoint
CREATE INDEX "custom_gpt_template_mappings_federal_state_id_index" ON "custom_gpt_template_mappings" USING btree ("federal_state_id");--> statement-breakpoint
CREATE INDEX "school_federal_state_id_index" ON "school" USING btree ("federal_state_id");--> statement-breakpoint
CREATE INDEX "shared_character_chat_usage_tracking_character_id_index" ON "shared_character_chat_usage_tracking" USING btree ("character_id");--> statement-breakpoint
CREATE INDEX "shared_character_chat_usage_tracking_user_id_index" ON "shared_character_chat_usage_tracking" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "shared_character_chat_usage_tracking_created_at_index" ON "shared_character_chat_usage_tracking" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "shared_school_conversation_user_id_index" ON "shared_school_conversation" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "shared_school_conversation_usage_tracking_shared_school_conversation_id_index" ON "shared_school_conversation_usage_tracking" USING btree ("shared_school_conversation_id");--> statement-breakpoint
CREATE INDEX "shared_school_conversation_usage_tracking_user_id_index" ON "shared_school_conversation_usage_tracking" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "shared_school_conversation_usage_tracking_created_at_index" ON "shared_school_conversation_usage_tracking" USING btree ("created_at");