# run 'docker compose -f ./devops/docker/monitoring.yml up' from project root folder
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval: '15s'
  evaluation_interval: '15s'
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
        labels:
          prometheus: prom
storage:
  tsdb:
    out_of_order_time_window: '30m'
# https://prometheus.io/docs/guides/opentelemetry/
otlp:
  promote_all_resource_attributes: false
  keep_identifying_resource_attributes: true
  # Recommended attributes to be promoted to labels.
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment
    - deployment.environment.name
    - k8s.cluster.name
    - k8s.container.name
    - k8s.cronjob.name
    - k8s.daemonset.name
    - k8s.deployment.name
    - k8s.job.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.replicaset.name
    - k8s.statefulset.name
