name: Delete Old Conversations
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  delete-conversations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          API_KEY: op://telli Engineering/.env.production chatbot/API_KEY
      - name: Call Delete Conversations Endpoint
        run: |
          # Make the API call and store the full response
          RESPONSE=$(curl -s -X DELETE https://chat.telli.schule/api/v1/admin/delete-conversation \
            -H "Authorization: Bearer ${{ env.API_KEY }}" \
            -H "Content-Type: application/json")

          # Get the status code separately
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE https://chat.telli.schule/api/v1/admin/delete-conversation -H "Authorization: Bearer ${{ env.API_KEY }}")

          # Check if the request was successful
          if [[ $STATUS_CODE -lt 200 || $STATUS_CODE -ge 300 ]]; then
            echo "Error: Received status code $STATUS_CODE"
            echo "Response: $RESPONSE"
            exit 1
          fi

          # Extract and display the count
          COUNT=$(echo $RESPONSE | jq '.count')
          echo "Successfully deleted $COUNT expired conversations"
